baseurl: http://www.fgl.imb.br/
metaDataFormat: yaml
title: Galeria de fotos FGL Galpões
theme: blist-hugo-theme
DefaultContentLanguage: pt
params:
  ascentColor: bg-blue-100
  comments:
    category: ''
    categoryid: ''
    emitmetadata: ''
    inputposition: ''
    mapping: ''
    reactionsenabled: ''
    repo: ''
    repoid: ''
    strict: ''
    system: giscus
    theme: ''
  copyright: Copyright © 2021 - Katheryn Fox · All rights reserved
  darkModeToggle: yes
  enableSearch: yes
  favicon: /favicon.svg
  frontBundle: blog
  hideMeta: no
  hideOtherLanguages: no
  hidePageThumbnail: no
  homepage:
    social:
      description: I work on everything coding and tweet developer memes
      icons:
        - url: https://twitter.com/
          website: twitter
      title: Follow me
  searchKeys:
    - tags
    - date
    - categories
    - summary
    - content
    - link
    - author
  toc: no
build:
  writeStats: yes
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: dracula